name: Generate snake

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "37 5 * * *"

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-dark.svg?color_snake=#ffffff&color_dots=#21262d,#30363d,#484f58,#6e7681,#8b949e,#c9d1d9
            dist/snake-light.svg?color_snake=#000000&color_dots=#ebedf0,#d0d7de,#9da7b1,#6e7781,#444c56,#21262d

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
