name: Generate snake

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "37 5 * * *"

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-snake.svg?theme=github-dark&color_snake=#a78bfa&color_dots=#21262d

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
